import test from 'node:test';
import assert from 'node:assert/strict';
import { recordReview, recordDisposal, recordReuse, pendingItems, sustainabilityTotals } from '../src/sustainability.js';
function seed(unit='un',needed=10) { return [{id:'MOB-001',status:'Concluída',items:[{id:'CAT-001',name:'Disjuntor',unit,needed}],history:[]},{id:'MOB-002',status:'Em mobilização',items:[{id:'CAT-001',unit,needed:3}],history:[]}]; }
const review = (extra={}) => ({quantities:{reusable:5,repair:0,discard:3,consumed:0,waste:1,lost:1},type:'Equipamentos eletroeletrônicos',unitCost:20,date:'2026-10-06',responsible:'Lucas',notes:'Dano e extravio registrados',confirmed:true,...extra});
const receipt = {destinationId:'electronics',date:'2026-10-06',responsible:'Lucas',evidence:'DEMO-001',confirmed:true};
const reuse = {targetId:'MOB-002',quantity:3,date:'2026-10-06',responsible:'Lucas',confirmed:true};
test('concluded works queue every unchecked material and review does not mutate the original',()=>{const records=seed();assert.equal(pendingItems(records[0]).length,1);const updated=recordReview(records,'MOB-001','CAT-001',review());assert.equal(pendingItems(updated[0]).length,0);assert.equal(pendingItems(records[0]).length,1);assert.equal(updated[0].history.length,1);});
test('quantities must balance, no negative or fractional units, and confirmation is required',()=>{assert.throws(()=>recordReview(seed(),'MOB-001','CAT-001',review({quantities:{...review().quantities,reusable:4}})));assert.throws(()=>recordReview(seed(),'MOB-001','CAT-001',review({quantities:{...review().quantities,reusable:4.5,discard:3.5}})));assert.throws(()=>recordReview(seed(),'MOB-001','CAT-001',review({confirmed:false})));assert.throws(()=>recordReview(seed(),'MOB-001','CAT-001',review({notes:''})));});
test('meters accept decimal quantities but are not added to units',()=>{const r=recordReview(seed('m',10),'MOB-001','CAT-001',review({quantities:{reusable:5.25,repair:0,discard:2.75,consumed:0,waste:1,lost:1}}));const t=sustainabilityTotals(r);assert.equal(t.m.reusable,5.25);assert.equal(t.un.reusable,undefined);});
test('triage and delivery cannot be registered twice; delivery needs compatible point and evidence',()=>{let r=recordReview(seed(),'MOB-001','CAT-001',review());assert.throws(()=>recordReview(r,'MOB-001','CAT-001',review()));assert.equal(sustainabilityTotals(r).un.disposed,0);assert.throws(()=>recordDisposal(r,'MOB-001','CAT-001',{...receipt,destinationId:'metal'}));assert.throws(()=>recordDisposal(r,'MOB-001','CAT-001',{...receipt,evidence:''}));r=recordDisposal(r,'MOB-001','CAT-001',receipt);assert.equal(sustainabilityTotals(r).un.disposed,3);assert.throws(()=>recordDisposal(r,'MOB-001','CAT-001',receipt));assert.equal(r[0].items[0].review.disposal.evidence,'DEMO-001');});
test('new use is distinct from apt material and limited by origin and destination quantities',()=>{let r=recordReview(seed(),'MOB-001','CAT-001',review());assert.equal(sustainabilityTotals(r).un.reused,0);r=recordReuse(r,'MOB-001','CAT-001',reuse);const t=sustainabilityTotals(r);assert.equal(t.un.reused,3);assert.equal(t.un.available,2);assert.equal(t.estimatedSavings,60);assert.equal(t.un.waste,1);assert.equal(t.un.lost,1);assert.throws(()=>recordReuse(r,'MOB-001','CAT-001',reuse));assert.throws(()=>recordReuse(r,'MOB-001','CAT-001',{...reuse,targetId:'MOB-001'}));});
test('multiple source records cannot exceed the target material requirement',()=>{let r=seed();r.push({...r[0],id:'MOB-003',items:r[0].items.map(i=>({...i}))});r=recordReview(r,'MOB-001','CAT-001',review());r=recordReview(r,'MOB-003','CAT-001',review());r=recordReuse(r,'MOB-001','CAT-001',reuse);assert.throws(()=>recordReuse(r,'MOB-003','CAT-001',{...reuse,quantity:1}));});
test('missing unit cost never creates an invented saving; records survive JSON persistence',()=>{let r=recordReview(seed(),'MOB-001','CAT-001',review({unitCost:null}));r=recordReuse(r,'MOB-001','CAT-001',reuse);const t=sustainabilityTotals(JSON.parse(JSON.stringify(r)));assert.equal(t.estimatedSavings,0);assert.equal(t.missingCosts,1);assert.equal(t.un.reused,3);});
