import React, { useEffect, useRef, useState } from 'react';
import { disposalTypes, suggestDisposalType } from './Disposal.jsx';
import { outcomes, pendingItems, round, eligibleDestinations, sustainabilityTotals } from './sustainability.js';
const today = () => new Date().toLocaleDateString('en-CA');
const amount = n => Number(n || 0).toLocaleString('pt-BR');
const info = (item, materials) => ({ ...materials.find(m => m.id === item.id), ...item, name: item.name || materials.find(m => m.id === item.id)?.name || item.id, unit: item.unit || materials.find(m => m.id === item.id)?.unit || '' });
export function MobilizationTriage({ records, materials, onReview, onReuse, user, go }) {
  const [selected, setSelected] = useState(null);
  const [query, setQuery] = useState('');
  const groups = records.filter(m => pendingItems(m).length).filter(m => `${m.id} ${m.work} ${m.responsible}`.toLowerCase().includes(query.toLowerCase()));
  const mob = records.find(m => m.id === selected?.mobId);
  const item = mob?.items.find(i => i.id === selected?.itemId && !i.review);
  return <section className="cycle-workspace"><div className="triage-intro"><div><span className="eyebrow">ECONOMIA CIRCULAR · MOBILIZAÇÕES</span><h2>Materiais de obras concluídas</h2><p>Toda mobilização concluída permanece nesta fila até que todos os materiais tenham sido conferidos.</p></div><span className="pill orange">{records.filter(m => pendingItems(m).length).length} mobilizações pendentes</span></div><label className="search-input cycle-search"><input aria-label="Buscar mobilização para triagem" value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar mobilização por código, obra ou responsável" /></label>{groups.map(m => <section className="card cycle-group" key={m.id}><div className="section-heading"><div><span className="material-code">{m.id} · Obra concluída</span><h2>{m.work}</h2><p className="subtle">{m.items.filter(i => i.review).length} de {m.items.length} materiais conferidos</p></div><span className="pill orange">{pendingItems(m).length} pendentes</span></div>{pendingItems(m).map(i => { const material = info(i, materials); return <article className="triage-row" key={i.id}><div><h3>{material.name}</h3><p>{i.id} · {amount(i.needed)} {material.unit} enviados</p></div><button className="button primary" aria-label={`Conferir ${i.id} de ${m.id}`} onClick={() => setSelected({ mobId: m.id, itemId: i.id })}>Conferir material →</button></article>; })}</section>)}{!groups.length && <div className="card empty"><h3>{query ? 'Nenhuma mobilização encontrada' : 'Nenhuma mobilização pendente'}</h3><p>Conclua a execução da obra em Mobilizações para conferir os materiais vinculados.</p><button className="button secondary" onClick={() => go('Mobilizações')}>Ver mobilizações</button></div>}{item && <ReviewForm key={`${mob.id}-${item.id}`} mob={mob} item={info(item, materials)} onSave={review => { if (onReview(mob.id, item.id, review)) { setSelected(null); if (review.quantities.discard > 0 || review.quantities.repair > 0) go('Destinação sustentável'); } }} onClose={() => setSelected(null)} user={user} />}
  <section className="card cycle-group"><div className="section-heading"><div><h2>Materiais disponíveis para reutilização</h2><p className="subtle">Registre o novo uso para contabilizar reutilização e compra evitada estimada.</p></div></div>{records.flatMap(m => m.items.filter(i => i.review && i.review.quantities.reusable > i.review.reuses.reduce((sum,e)=>sum+e.quantity,0)).map(i => <ReuseForm key={`${m.id}-${i.id}`} mob={m} item={info(i, materials)} records={records} onSave={event => onReuse(m.id,i.id,event)} user={user} />))}{!records.some(m => m.items.some(i => i.review && i.review.quantities.reusable > i.review.reuses.reduce((sum,e)=>sum+e.quantity,0))) && <p className="empty">Nenhum material conferido disponível para um novo uso.</p>}</section></section>;
}
function ReviewForm({ mob, item, onSave, onClose, user }) {
  const sectionRef = useRef(null);
  useEffect(() => { sectionRef.current?.focus(); sectionRef.current?.scrollIntoView?.({ block: 'start', behavior: 'smooth' }); }, []);
  const [quantities, setQuantities] = useState(Object.fromEntries(outcomes.map(([key])=>[key,0])));
  const [type, setType] = useState(suggestDisposalType({ descricao: item.name, categoria: item.category }));
  const sum = round(Object.values(quantities).reduce((a,b)=>a+b,0));
  const hasDest = quantities.discard > 0 || quantities.repair > 0;
  return <section className="card cycle-review" ref={sectionRef} tabIndex={-1} aria-label={`Conferência de ${item.id}`}><div className="section-heading"><div><span className="eyebrow">{mob.id} · {item.id}</span><h2>{item.name}</h2></div><button className="button secondary" onClick={onClose}>Cancelar conferência</button></div><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);onSave({ quantities, type, unitCost: null, date:data.get('date'), responsible:data.get('responsible'), notes:data.get('notes'), confirmed:data.get('confirmed')==='on' });}}><p className="form-hint">Distribua os {amount(item.needed)} {item.unit} enviados. Informe consumo, perda ou desperdício separadamente do material retornado.</p><div className="quantity-outcomes">{outcomes.map(([key,label])=><label key={key}>{label} ({item.unit})<input type="number" aria-label={`${label} em ${item.unit}`} min="0" max={item.needed} step={item.unit==='un'?'1':'0.01'} required value={quantities[key]} onChange={e=>setQuantities({...quantities,[key]:Number(e.target.value)})} /></label>)}</div><p className={`quantity-check ${sum===round(item.needed)?'green':'orange'}`} role="status">Classificado: {amount(sum)} / {amount(item.needed)} {item.unit}{sum===round(item.needed)?' · Quantidades conferidas':' · Ajuste as quantidades para fechar o total'}</p>{hasDest && <><label>Tipo de material para destinação<select value={type} onChange={e=>setType(e.target.value)} required><option value="">Selecione o tipo</option>{disposalTypes.map(t=><option key={t}>{t}</option>)}</select><small>Sugestão pelo cadastro. Corrija em caso de contaminação.</small></label><div className="form-hint">{quantities.repair>0 && <p><strong>Recuperação:</strong> encaminhe à avaliação técnica / manutenção antes de descartar. Materiais contaminados exigem orientação ambiental especializada.</p>}{quantities.discard>0 && <p><strong>Destinos sugeridos:</strong> {eligibleDestinations(type).map(d=>`${d.name} — ${d.location}`).join('; ') || 'Selecione a classificação para consultar os pontos.'}</p>}</div></>}<div className="rfid-form-columns"><label>Data da conferência<input name="date" type="date" defaultValue={today()} required /></label><label>Responsável pela conferência<input name="responsible" defaultValue={user.name} required pattern=".*\S.*" /></label></div><label>Observações / motivo da perda ou desperdício<input name="notes" required={quantities.waste>0||quantities.lost>0} pattern={quantities.waste>0||quantities.lost>0?'.*\\S.*':undefined} placeholder="Descreva a condição e as ocorrências" /></label><label className="checkbox-label"><input name="confirmed" type="checkbox" required />Confirmo as quantidades e a conferência demonstrativa.</label><button className="button primary" disabled={sum!==round(item.needed)}>Salvar triagem e próximo passo</button></form></section>;
}
function ReuseForm({ mob, item, records, onSave, user }) {
  const [message, setMessage] = useState('');
  const available=round(item.review.quantities.reusable-item.review.reuses.reduce((sum,e)=>sum+e.quantity,0));
  const targets=records.filter(m=>m.id!==mob.id&&m.status==='Em mobilização'&&m.items.some(i=>i.id===item.id));
  return <details className="cycle-history"><summary>{item.name} · {available} {item.unit} aptos · origem {mob.id}</summary><form className="cycle-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);if(onSave({quantity:Number(d.get('quantity')),targetId:d.get('target'),date:d.get('date'),responsible:d.get('responsible'),confirmed:d.get('confirmed')==='on'})){setMessage('Reutilização registrada e vinculada ao novo uso.');e.currentTarget.reset();}}}><label>Mobilização do novo uso<select name="target" required><option value="">Selecione a mobilização em andamento</option>{targets.map(m=><option value={m.id} key={m.id}>{m.id} · {m.work}</option>)}</select></label>{!targets.length && <p className="form-hint">Inicie uma nova mobilização que contenha este material para registrar seu reaproveitamento.</p>}<label>Quantidade reutilizada ({item.unit})<input name="quantity" type="number" min={item.unit==='un'?'1':'0.01'} max={available} step={item.unit==='un'?'1':'0.01'} required /></label><label>Data do novo uso<input name="date" type="date" defaultValue={today()} required /></label><label>Responsável<input name="responsible" defaultValue={user.name} required pattern=".*\S.*" /></label><label className="checkbox-label"><input name="confirmed" type="checkbox" required />Confirmo o novo uso demonstrativo do material.</label><button className="button primary" disabled={!targets.length}>Registrar reutilização</button>{message && <p role="status">{message}</p>}</form></details>;
}
function DestinationDialog({ title, onClose, children }) {
  const ref = useRef(null);
  useEffect(() => {
    const previous = document.activeElement;
    const dialog = ref.current;
    dialog.showModal();
    return () => { dialog.close(); previous?.focus(); };
  }, []);
  return <dialog ref={ref} className="modal destination-dialog" aria-label={title} onCancel={onClose}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="Fechar validação de destinação" onClick={onClose}>✕</button></div>{children}</dialog>;
}
export function MobilizationDestinations({ records, materials, onDispose, user }) {
  const [selected, setSelected] = useState(null);
  const [query, setQuery] = useState('');
  const [feedback, setFeedback] = useState('');
  const pending=records.flatMap(m=>m.items.filter(i=>i.review && (i.review.quantities.discard>0&&!i.review.disposal||i.review.quantities.repair>0)).map(i=>({mob:m,item:info(i,materials)})));
  const filtered=pending.filter(({mob,item})=>`${item.name} ${item.id} ${mob.id} ${mob.work}`.toLowerCase().includes(query.trim().toLowerCase()));
  const current=pending.find(({mob,item})=>`${mob.id}:${item.id}`===selected);
  return <section className="cycle-workspace"><div className="info-banner"><div><strong>Pontos demonstrativos · validar antes do uso real</strong><p>Selecione um material para consultar o destino e validar a entrega. O descarte só entra nos indicadores após confirmar responsável, data e comprovante.</p></div></div>{feedback&&<p className="rfid-feedback" role="status">{feedback}</p>}<section className="card cycle-group"><div className="section-heading"><div><h2>Materiais para destinação ou recuperação</h2><p className="subtle">Abra um material para conferir os próximos passos.</p></div><span className="count">{pending.length}</span></div><div className="filters"><label className="search-input"><input aria-label="Buscar material para destinação" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar material, código ou mobilização" /></label></div><div className="destination-list">{filtered.map(({mob,item})=><button className="destination-list-item" key={`${mob.id}-${item.id}`} aria-label={`Validar destinação de ${item.id} de ${mob.id}`} onClick={()=>{setSelected(`${mob.id}:${item.id}`);setFeedback('');}}><div><strong>{item.name}</strong><small>{item.id} · {mob.id} · {mob.work}</small></div><div className="destination-list-status">{item.review.quantities.discard>0&&!item.review.disposal&&<span className="pill orange">{amount(item.review.quantities.discard)} {item.unit} para destinação</span>}{item.review.quantities.repair>0&&<span className="pill neutral">{amount(item.review.quantities.repair)} {item.unit} para recuperação</span>}</div><span className="destination-list-action">Abrir validação →</span></button>)}</div>{!filtered.length&&<div className="empty"><h3>{query?'Nenhum material encontrado':'Nenhum material aguardando destinação'}</h3><p>{query?'Tente outro nome, código ou mobilização.':'Os materiais que precisarem de destinação aparecerão aqui após a triagem.'}</p>{query&&<button className="button secondary" onClick={()=>setQuery('')}>Limpar busca</button>}</div>}</section>{current&&<DestinationDialog title={`Validação de destinação · ${current.item.name}`} onClose={()=>setSelected(null)}><DestinationForm mob={current.mob} item={current.item} onSave={receipt=>{if(onDispose(current.mob.id,current.item.id,receipt)){setSelected(null);setFeedback('Destinação confirmada e registrada nos indicadores.');}}} user={user} /></DestinationDialog>}</section>;
}
function DestinationForm({ mob,item,onSave,user }) {
  const points=eligibleDestinations(item.review.type);
  return <section className="card cycle-group"><div className="section-heading"><div><span className="eyebrow">{mob.id} · {item.id}</span><h2>{item.name}</h2><p className="subtle">{mob.work} · {item.review.type}</p></div></div>{item.review.quantities.repair>0 && <div className="form-hint repair-note"><strong>{item.review.quantities.repair} {item.unit} para recuperação</strong><p>Ponto recomendado: avaliação técnica / oficina de manutenção demonstrativa. {item.review.type==='Material com óleo ou contaminação'?'Solicite avaliação ambiental especializada antes do manuseio.':'Avalie possibilidade de reparo antes de optar pelo descarte.'}</p></div>}{item.review.quantities.discard>0&&!item.review.disposal && <form className="cycle-form" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);onSave({destinationId:d.get('destination'),date:d.get('date'),responsible:d.get('responsible'),evidence:d.get('evidence'),confirmed:d.get('confirmed')==='on'});}}><p>{item.review.quantities.discard} {item.unit} não reutilizáveis · selecione o ponto de destinação</p>{points.map(d=><label className="destination-card" key={d.id}><input type="radio" name="destination" value={d.id} required /><div><span className="pill green">{d.route}</span><h3>{d.name}</h3><p>{d.location}</p><small>{d.guidance}</small></div></label>)}<label>Data da entrega<input name="date" type="date" defaultValue={today()} required /></label><label>Responsável pela entrega<input name="responsible" defaultValue={user.name} required pattern=".*\S.*" /></label><label>Comprovante / protocolo de recebimento<input name="evidence" required pattern=".*\S.*" placeholder="Identificação do comprovante demonstrativo" /></label><label className="checkbox-label"><input name="confirmed" type="checkbox" required />Confirmo a entrega demonstrativa ao destino selecionado.</label><button className="button primary" disabled={!points.length}>Confirmar destinação</button></form>}</section>;
}
export function SustainabilityIndicators({ records, materials }) {
  const totals=sustainabilityTotals(records);
  const metrics=[['Aptos para reutilização','reusable'],['Reutilizados em outra mobilização','reused'],['Disponíveis para novo uso','available'],['Destinação confirmada','disposed'],['Aguardando destinação','pendingDisposal'],['Desperdiçados','waste'],['Não localizados / perdidos','lost'],['Consumidos na obra','consumed'],['Aguardando recuperação','repair']];
  return <section className="cycle-workspace"><div className="triage-intro"><div><span className="eyebrow">SUSTENTABILIDADE COM RASTREABILIDADE</span><h2>Resultados registrados no ciclo dos materiais</h2><p>{totals.reviewed} materiais conferidos · {totals.pending} materiais aguardando triagem</p></div></div><div className="metric-grid">{metrics.map(([label,key])=><section className="card cycle-metric" key={key}><h3>{label}</h3><strong>{amount(key==='pendingDisposal'?(totals.un.discard||0)-(totals.un.disposed||0):totals.un[key])} <small>un</small></strong><strong>{amount(key==='pendingDisposal'?(totals.m.discard||0)-(totals.m.disposed||0):totals.m[key])} <small>m</small></strong></section>)}</div><section className="card cycle-group"><div className="section-heading"><div><h2>Compra evitada estimada</h2><p className="subtle">Somente reutilizações confirmadas × custo de reposição previamente registrado.</p></div><strong>{totals.estimatedSavings.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong></div><p className="form-hint">Estimativa de compra evitada, não economia financeira auditada. {totals.missingCosts} materiais reutilizados sem custo informado não entram nesta estimativa. Metros e unidades são contabilizados separadamente.</p></section><section className="card cycle-group"><div className="section-heading"><h2>Registros por mobilização e material</h2></div><div className="table-scroll"><table><thead><tr><th>Mobilização / material</th><th>Resultado da triagem</th><th>Conferência</th><th>Destinação / reutilização</th></tr></thead><tbody>{records.flatMap(m=>m.items.filter(i=>i.review).map(i=><tr key={`${m.id}-${i.id}`}><td>{m.id} · {info(i,materials).name}<small>{m.work}</small></td><td>{outcomes.filter(([k])=>i.review.quantities[k]>0).map(([k,label])=><small key={k}>{label}: {i.review.quantities[k]} {i.unit}</small>)}</td><td>{i.review.responsible}<small>{i.review.date}</small><small>{i.review.notes}</small></td><td>{i.review.disposal?<><span>{i.review.disposal.destination}</span><small>Comprovante: {i.review.disposal.evidence}</small><small>{i.review.disposal.date} · {i.review.disposal.responsible}</small></>:'Sem entrega confirmada'}{i.review.reuses.map((e,n)=><small key={n}>Reuso: {e.quantity} {i.unit} → {e.targetId} · {e.date} · {e.responsible}</small>)}</td></tr>))}</tbody></table>{!totals.reviewed&&<p className="empty">Os indicadores serão preenchidos após as conferências.</p>}</div></section></section>;
}
